import "./globals.css";
import { Inter } from "next/font/google";
import { Amplify, Auth } from "aws-amplify";
import awsExports from "@/aws-exports";
import dotenv from "dotenv";

dotenv.config();

const inter = Inter({ subsets: ["latin"] });

console.log(process.env.REACT_APP_AWS_PROJECT_REGION);
console.log(process.env.REACT_APP_AWS_USER_POOLS_ID);
console.log(process.env.REACT_APP_CLIENT_ID);

export const metadata = {
  title: "Project X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
