import "./globals.css";
import { Inter } from "next/font/google";
import { Amplify } from "aws-amplify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(process.env.REACT_APP_REGION);
  Amplify.configure({
    Auth: {
      region: process.env.REACT_APP_REGION,
      userPoolId: process.env.REACT_APP_USER_POOL_ID,
      userPoolWebClientId: process.env.REACT_APP_USER_POOL_APP_CLIENT_ID,
    },
  });

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
