/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
  aws_project_region: "us-east-1",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_57T4dM1ad",
  aws_user_pools_web_client_id: "4d77fi8jdfn4f72tm3v9mchekg",
  oauth: {},
};

export default awsExports;
